### Create a User
POST http://localHost:3000/auth/signup
Content-Type: application/json

{
  "email":"test4@fake.com",
  "password":"87654312",
  "other":456
}


### Find a paricular user with a given ID
GET http://localHost:3000/auth/4 HTTP/1.1


### Find all users with a given email
GET http://localHost:3000/auth?email=test4@fake.com HTTP/1.1


### Delete a user with a given id
DELETE  http://localHost:3000/auth/9


### Update a user
PATCH http://localHost:3000/auth/3
Content-Type: application/json

{
  "email":"bb@bb.com"
}

### Update a user
PATCH http://localHost:3000/auth/9
Content-Type: application/json

{
  "password":"bbbbmmmm"
}