### Create a User
POST http://localHost:3000/auth/signup
Content-Type: application/json

{
  "email":"ufsd@fake.com",
  "password":"123456789",
  "other":456
}

### Sign in as an existing user
POST http://localHost:3000/auth/signin
Content-Type: application/json

{
  "email":"y@fake.com",
  "password":"123456789"
}

### Get the currently signed in user
GET http://localHost:3000/auth/whoami HTTP/1.1

### Sign out
POST  http://localHost:3000/auth/signout HTTP/1.1

### Find a paricular user with a given ID
GET http://localHost:3000/auth/4 HTTP/1.1


### Find all users with a given email
GET http://localHost:3000/auth?email=test4@fake.com HTTP/1.1


### Delete a user with a given id
DELETE  http://localHost:3000/auth/9


### Update a user
PATCH http://localHost:3000/auth/3
Content-Type: application/json

{
  "email":"bb@bb.com"
}

### Update a user
PATCH http://localHost:3000/auth/7
Content-Type: application/json

{
  "password":"bbbbmmmm"
}


### Set a color
GET http://localHost:3000/auth/colors/red HTTP/1.1


### Get the Color
GET http://localHost:3000/auth/colors HTTP/1.1